apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    metadata:
      annotations:
        pod-mutating-webhook.spring.io/inject: "yes"
    spec:
      containers:
      - image: dsyer/demo
        name: demo
        volumeMounts:
        - name: demo-config
          mountPath: /app/config/
      volumes:
      - name: demo-config
        configMap:
          name: demo-config