apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - image: dsyer/demo
        name: demo
        volumeMounts:
        - name: demo-config
          mountPath: /app/config/
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
      volumes:
      - name: demo-config
        configMap:
          name: demo-config
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels.properties"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
