apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    metadata:
      annotations:
        pod-mutating-webhook.spring.io/inject: "yes"
    spec:
      containers:
      - name: demo
        env:
        - name: EXT_LIBS
          value: /app/ext
        